#-------------------------------------
# Github Action part 1 _basics

name: My-Githubactionbasics
env:
  APPLICATION_NAME: "MyFlaskApp"
  DEPLOY-PACKAGE-NAME: "flask-app-ver-${{ github.sha }}"
on:
  push:
    branches: 
      - main


jobs:
  my_testing:
    runs-on: [ubuntu-latest]

    steps:
      - name: Print nice message
        run: echo "hello world"

      - name: Execute few commands
        run : |
          echo "Hello Message1"
          echo "Hello Message2"
          echo "Printing Global ENV variable ${{ env.DEPLOY-PACKAGE-NAME }}"

      - name: Git clone my repo
        uses: actions/checkout@v1
          
      

  my_deploy:
    runs-on: [ubuntu-latest]
    needs: [my_testing]
    env: 
      VAR1 : "Job Variable 1"
      VAR2 : "Job Variable 2"
      
    


    steps:
      - name: Print nice message from deploy
        run: echo "Tets testing"

      - name: List current folder
        run: ls -la

      - name: print some more info
        run: echo " {{ env.VAR1 }}
        

  
